version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:6

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-cache
          paths:
            - ~/.npm
      - run:
          name: Run tests
          command: npm run ci
